DECLARE
  vNome TALUNO.nome%TYPE := 'Marcinho';
  vCidade TALUNO.CIDADE%TYPE;
BEGIN
  SELECT CIDADE
  INTO vCidade
  FROM TALUNO WHERE NOME = VNOME;
  EXCEPTION
  WHEN No_Data_Found THEN
    Raise_Application_Error(-20001, 'ALUNO INEXISTENTE!' || ' COD: ' || SQLCODE || ' - ' || SQLERRM);
  WHEN Too_Many_Rows THEN
    Raise_Application_Error(-20002,'ALUNO DUPLICADO');
  WHEN OTHERS THEN
    Raise_Application_Error(-20003, 'EXCEÇÃO DESCONHECIDA');
END;

--COMANDO [RAISE nome do erro] LANÇA UMA EXCEÇÃO

/* DEVE-SE USAR O PRAGMA PARA NOMEAR ALGUNS ERROS, PORQUE ALGUNS TIPOS DE ERROS POSSUÍ CÓDIGO, MAS NÃO
POSSUE NOME */

--PRAGMA EXCEPTION_INIT(NOME_VAR_EXCEPTION, COD-A-SER-ASSOCIADO);

DECLARE
  vNome TALUNO.nome%TYPE := 'VALDO';
  vCidade TALUNO.CIDADE%TYPE;
  x NUMBER;
BEGIN
  SELECT CIDADE
  INTO vCidade
  FROM TALUNO WHERE COD_ALUNO = 44;
  X := 0/0;
  EXCEPTION
  WHEN No_Data_Found THEN
    Raise_Application_Error(-20001, 'ALUNO INEXISTENTE!' || ' COD: ' || SQLCODE || ' - ' || SQLERRM);
  WHEN Too_Many_Rows THEN
    Raise_Application_Error(-20002,'ALUNO DUPLICADO');
  WHEN OTHERS THEN
    Raise_Application_Error(-20003, 'EXCEÇÃO DESCONHECIDA');
END;

DECLARE
  vNome TALUNO.NOME%TYPE;
  EX EXCEPTION;
 BEGIN
     SELECT NOME INTO vNome FROM TALUNO WHERE cod_aluno = 44;
     IF(VNOME = 'VALDO') THEN
      Dbms_Output.PUT_LINE('TROCA DE NOME DO CÓDIGO 44');
      RAISE EX;
     END IF;
     EXCEPTION
      WHEN EX THEN
        Dbms_Output.PUT_LINE('TROCA DE NOME DO CÓDIGO 44');
        UPDATE TALUNO SET NOME = 'CAIO' WHERE COD_ALUNO = 44;
 END;

SELECT * FROM TALUNO;

DECLARE
  ERRO EXCEPTION;
  PRAGMA EXCEPTION_INIT(ERRO, -1722);
 BEGIN
  INSERT INTO TALUNO VALUES ('M','FELIPE','CIDADE','837');
 EXCEPTION
  WHEN Invalid_Number THEN
    Raise_Application_Error(-20220,'invalid!');
  WHEN ERRO THEN
    Raise_Application_Error(-20221,'ERRO!');
 END;