DECLARE
TYPE TALUNO_RECORD_TYPE IS RECORD
(
  COD_ALUNO TALUNO.COD_ALUNO%TYPE,
  NOME TALUNO.NOME%TYPE,
  CIDADE TALUNO.CIDADE%TYPE
);
T_ALUNO_RECORD TALUNO_RECORD_TYPE;
BEGIN
  T_ALUNO_RECORD.NOME := 'FELIPE';
  Dbms_Output.PUT_LINE(T_ALUNO_RECORD.NOME);
END;

DECLARE
  TYPE T_ALUNO_ASSOCIATIVE IS TABLE OF TALUNO%ROWTYPE INDEX BY BINARY_INTEGER;
  TYPE T_NUMERO_ASSOCIATIVE_ARRAY IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;
  T_ALUNO_ASSOCIATIVE_ARRAYS T_ALUNO_ASSOCIATIVE;
BEGIN
        T_ALUNO_ASSOCIATIVE_ARRAYS(1).NOME := 'FELIPE CÉSAR';
        Dbms_Output.PUT_LINE(T_ALUNO_ASSOCIATIVE_ARRAYS(1).NOME);
END;

DECLARE
  TYPE AR IS VARRAY(6) OF TALUNO%ROWTYPE;
  AR_VAR AR := AR();
BEGIN
  AR_VAR.EXTEND();
  AR_VAR(1).NOME := 'FELIPE';
  Dbms_Output.PUT_LINE(AR_VAR(1).NOME);
END;

DECLARE
  TYPE T_ALUNO_TABLE_TYPE IS TABLE OF VARCHAR2(50);
  T_ALUNO_TABLE T_ALUNO_TABLE_TYPE := T_ALUNO_TABLE_TYPE();

BEGIN
  T_ALUNO_TABLE.extend;
  T_ALUNO_TABLE(1) := 'FELIPE GOMES';
  Dbms_Output.PUT_LINE(T_ALUNO_TABLE(1));
END;

DECLARE
  CURSOR C1 IS
    SELECT * FROM TALUNO;
  REC_ALUNO TALUNO%ROWTYPE;
BEGIN
  OPEN C1;
  LOOP
    FETCH C1 INTO REC_ALUNO;
    IF C1%FOUND  THEN
      Dbms_Output.PUT_LINE('CURSOR PODE CONTINUAR');
    ELSE
        Dbms_Output.PUT_LINE('FIM DO CURSOR');
    END IF;
    EXIT WHEN C1%NOTFOUND;
    Dbms_Output.PUT_LINE(REC_ALUNO.NOME);
  END LOOP;
  CLOSE C1;
END;

DECLARE
  CURSOR C2 IS
  SELECT * FROM TALUNO;

  RECALUNO TALUNO%ROWTYPE;

BEGIN
   FOR RECALUNO IN C2 LOOP
   Dbms_Output.PUT_LINE(RECALUNO.NOME);
   END LOOP;

END;

